# 博客信息
blog_name: Jersey
slogan: Less is more
url: 

# 头像
avatar: /images/avatar.jpg

# 网站图标
favicon: /images/favicon.ico

# SEO
keywords: 日志，随笔

# 导航栏
nav:
  - name: 首页
    url: /
    target_blank: false # 不在新页面打开
  - name: 归档
    url: /archives
    target_blank: false
  - name: 标签
    url: /tags
    target_blank: false
  # - name: 友链
  #   url: /friends
  #   target_blank: false
  - name: 关于
    url: /about
    target_blank: false